version: '3.9'

services:
  client:
    build: ./client
    container_name: todomvc_client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client/:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api
      
  api:
    build: ./api
    container_name: todomvc_api
    env_file:
      - ./api/.env.local
    ports:
      - '80:80'
    volumes:
      - ./api/:/app
    
    # depends_on:
    #   - db

  # db:
  #   image: postgres:16-alpine
  #   container_name: quotes_db
  #   restart: always
  #   hostname: postgres
  #   ports:
  #     - '5432:5432'
  #   env_file:
  #     - ./env/db.env
  #   volumes:
  #     - data:/var/lib/postgresql/data

# volumes:
  # data: