// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: auth.sql

package database

import (
	"context"
)

const fetchMe = `-- name: FetchMe :one
select id, email from users where id=$1
`

type FetchMeRow struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) FetchMe(ctx context.Context, id int32) (FetchMeRow, error) {
	row := q.db.QueryRowContext(ctx, fetchMe, id)
	var i FetchMeRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const registerUser = `-- name: RegisterUser :exec
insert into users (email, password) values ($1, $2)
`

type RegisterUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) error {
	_, err := q.db.ExecContext(ctx, registerUser, arg.Email, arg.Password)
	return err
}
