// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Todo struct {
	ID        int32  `json:"id"`
	Text      string `json:"text"`
	Completed bool   `json:"completed"`
	AuthorID  int32  `json:"author_id"`
}

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
